bot:
  nick: A`Gario
  login: A`Gario
  realname: A`Gario
  version: A`Gario - Bot by likcoras
  password: password

server:
  host: irc.rizon.net
  port: 6697
  ssl: true
  trust: true

channels:
- "#agario"

others:
  apiKey: apikey
  ownerNick: likcoras
  ownerHost: tis.very.bored